import { Inter } from "next/font/google";
import "./globals.scss";
import "./poemspage.styles.scss";
import "./haikupage.styles.scss";
import "./components.scss"
import "./verifypage.scss"
import { Navbar } from "@/components";
import StoreProvider from "./StoreProvider";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
            <div className="app" >
              <Navbar />
              {children}
              {/* <PaymentOverlay /> */}
            </div>
        </StoreProvider>
      </body>
    </html>
  );
}
